### ISSUE TITLE
hard coded directories - convert to relative ?

### ISSUE THREAD

**Issue by privaterra** [akre96/cdc_overdose#1]
I'm trying to run the great R code you have developed to generate the graphs in the report. However, i'm running into an issue that there are several hard coded directory files in The CDC_monthly_recovery_analysis.R.

/data/CDC_2020/

If that works, then I want to add Oklahoma to the list of graphs. It an important member of congress is from that State...

**Comment by akre96** [comment]
Hello! Appreciate your interest in this work.

If you change the "root" variable in all of the R scripts (it is near the top of the files) to point to the directory of the project code on your machine it should solve your problem. 

Let me know if that isn't the problem you are having or doesn't solve it.

**Comment by privaterra** [comment]
I did change the value for the ROOT directory, error still occurs .

It seems a couple lines include a - data/CDC - path that  caused the script to stop due to a directory / file not found error

Just wanted to point it out, as others likely too will run into the issue


-- Robert Guerra Cel/Tel +1 416 893 0377 Twitter: twitter.com/netfreedom Email: ***@***.***

**Comment by akre96** [comment]
Closing Issue -- resolved with your PR, thanks for that
